create table public.users
(
    id         bigint generated by default as identity
        primary key,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    role       varchar(255),
    username   varchar(255) not null
);

alter table public.users
    owner to postgres;

