CREATE TABLE user_auth_methods
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255),
    CONSTRAINT pk_user_auth_methods PRIMARY KEY (id)
);

ALTER TABLE user_auth_methods
    ADD CONSTRAINT uc_a1a66f2f768992eb0987be4d3 UNIQUE (user_id, provider);

ALTER TABLE user_auth_methods
    ADD CONSTRAINT FK_USER_AUTH_METHODS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    DROP COLUMN provider;

ALTER TABLE users
    DROP COLUMN provider_id;

ALTER TABLE users
    ALTER COLUMN last_name DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN password SET NOT NULL;